---
sidebar: sidebar
permalink: article_template.html # change this line
summary: # change this line
keywords: # change this line
---

= TITLE

:toc: macro
:hardbreaks:
:toclevels: 2
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords:

include::_include/toby-to-do/Management.command_center.copy_template_to_gallery.adoc[]


////
Create article process:

Using the example of an article with a Title of "File Name"


1. Create new .adoc file within the _include subfolder.  Duplicate and rename it based on 1.a. below.
1.a. Name should reflect the location the article will occupy on the sidebar (as defined in virtual-desktop-service/sidebar.yml and visible on the left at: https://docs.netapp.com/us-en/virtual-desktop-service/).  For example, will be in "Management > Deployments" and be titled "File Name", this file will be "virtual-desktop-service/_include/Management.Deployments.file_name.adoc"
2. Keep the Comments Section updated with the correct name of the "sub."" article(s) that use this content.  This way we can back-trace where content ends up.
2.a. In our example change "Used in: sub.article.template.adoc" to "Used in: sub.Management.Deployments.file_name.adoc"
3. Write the article and save it. In our example: "virtual-desktop-service/_include/Management.Deployments.file_name.adoc"
4. Duplicate this file (the one you're reading this text in) "virtual-desktop-service/sub.article_template.adoc" and name it the exact same as the file from step 1, but prepended with "sub."   (e.g. "virtual-desktop-service/sub.Management.Deployments.file_name.adoc")  Note that it should be saved int he root "virtual-desktop-service/ direction, not the _include" subdirectory.
5. Edit the following items above:
5.a. "permalink:" - make this the exact same as the .adoc file name from the _include folder adn change the file extension to ".html".  In our example: "Management.Deployments.file_name.html"
5.b. "summary:" - Enter a descriptive sentence or two, this is used in search results.
5.c. "keywords" - options, comma separated for search
5.d. "= TITLE" - Enter the title of the article which is used as the main header on the page.
5.e. "include::_include/Management.Deployments.file.name.adoc[]" change to the real path to the new _include .adoc file path.
