
////

Comments Sections:
Used in: sub.Reference.Release_Notes.vds_v6.0_release_notes.adoc

////
== VDS v6 release: Thursday August 12th, 2021
_Components:_ Virtual Desktop Service v6
_When:_ Thursday August 12, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service
* Enhancements to Cloud Insights functionality and context
* Improved backup schedule frequency handling
* Bug fix - resolve an issue for CwVmAutomation service checking config on service restart
* Bug fix - resolve an issue for DCConifg that did not allow saving configurations in certain scenarios
* Assorted proactive security and performance enhancements

== VDS v6 hotfix: Tuesday July 30th, 2021
_Components:_ Virtual Desktop Service v6
_When:_ Friday July 30th, 2021 at 7pm – 8pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Deployment template update to facilitate automation improvements

== VDS v6 release: Thursday July 29th, 2021
_Components:_ Virtual Desktop Service v6
_When:_ Thursday July 29th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service
* Bug fix - resolve an issue for VMware deployments where CWAgent didn't get installed as intended
* Bug fix - resolve an issue for VMware deployments where creating a server with the Data role didn't function as intended

== VDS v6 hotfix: Tuesday July 20th, 2021
_Components:_ Virtual Desktop Service v6
_When:_ Tuesday July 20th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service
* Remediate an issue causing abnormally large amount of API traffic in a certain configuration

== VDS 6.0 release: Thursday July 15th, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday July 15th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service
* Enhancement to Cloud Insights integration –capturing per-user performance metrics and displaying them in the User context
* Improvements to ANF provisioning automation – improved automated registration of NetApp as a provider in the customer’s Azure tenant
* Phrasing adjustment when creating a new AVD Workspace
* Assorted proactive security and performance enhancements

== VDS 6.0 release: Thursday June 24, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday June 4th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

NOTE: Due to scheduling around the 4th of July, the next VDS release will be on Thursday 7/15.

=== Virtual Desktop Service
* Updates to reflect that Windows Virtual Desktop (WVD) is now Azure Virtual Desktop (AVD)
* Bug fix for username formatting in Excel exports
* Improved configurations for custom branded HTML5 login pages
* Assorted proactive security and performance enhancements

=== Cost Estimators
* Updates to reflect that Windows Virtual Desktop (WVD) is now Azure Virtual Desktop (AVD)
* Updates to the reflect the more services/GPU VMs are available in new regions


== VDS 6.0 release: Thursday June 10, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday June 10th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Introduction of an additional HTML5 browser-based gateway/access point for VMs
* Improved user routing after deleting a host pool
* Bug fix for a scenario where importing an unmanaged host pool was not functioning as expected
* Assorted proactive security and performance enhancements

== VDS 6.0 release: Thursday June 10, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday June 10th, 2021 at 10pm eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Technical enhancements:
* Update the version of the .NET framework installed on each VM from v4.7.2 to v4.8.0
* Additional back-end enforcement of the use of https:// and TLS 1.2 or greater between the Local Control Plane team and any other entity
* Bug fix for the Delete Backup Operation in the Command Center – this now properly references the time zone of CWMGR1
* Rename the Command Center action from Azure File share to Azure Files share
* Naming convention updates in Azure Shared Image Gallery
* Improved concurrent user login count collection
* Update to outbound traffic allowed from CWMGR1, if restricting traffic outbound from the CWMGR1 VM
* If you are not restricting outbound traffic from CWMGR1, you do not have to make any updates here
* If you are restricting outbound traffic from CWMGR1, please allow access to vdctoolsapiprimary.azurewebsites.net. Note: you no longer need to allow access to vdctoolsapi.trafficmanager.net.

=== Deployment enhancements:
* Lay the foundation for future support of custom prefixes in server names
* Improved process automation and redundancies for Azure deployments
* Numerous deployment automation enhancements for Google Cloud Platform deployments
* Support for Windows Server 2019 in Google Cloud Platform deployments
* Bug fix for a subset of scenarios where the Windows 10 20H2 EVD image

=== Service delivery enhancements:
* Introduces Cloud Insights integration, delivering streaming performance data for User Experience, VM and Storage layers
* Introduces a function that allows you to quickly navigate to a VDS page visited recently
* Substantially improved list (Users, Groups, Servers, Applications, etc.) loading times for Azure deployments
* Introduces the ability to easily export lists of Users, Groups, Servers, Admins, Reports, etc.
* Introduces the ability to control what VDS MFA methods are available for customers (customer prefers email vs. SMS, for example)
* Introduces customizable “from” fields for VDS self-service password reset emails
* Introduces the option to only allow VDS self-service password reset emails to go to specified domains (company owned vs. personal, for example)
* Introduces an update that can prompt the user to add their email to their account so that they can use it or MFA/self-service password resets
* When starting a stopped deployment, start all VMs within the deployment as well
* Performance improvement for determining which IP address to assign to newly created Azure VMs

== VDS 6.0 release: Thursday May 27, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday May 27th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Introduce Start on Connect for Pooled session hosts in AVD host pools
* Introduce User performance metrics via Cloud Insights integration
* Display the Servers tab more prominently in the Workspaces module
* Allow the restoration of a VM via Azure Backup if the VM has been deleted from VDS
* Improved handling of Connect to Server functionality
* Improved handling of variables when creating and updating certificates automatically
* Bug fix for an issue where clicking an X in a drop-down menu didn’t clear the selection as expected
* Improved reliability and automatic error handling for SMS message prompts
* Update to the User Support role – this can now terminate processes for a logged in user
* Assorted proactive security and performance enhancements


== VDS 6.0 release: Thursday May 13, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday May 13th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Introduction of additional AVD host pool properties
* Introduce additional automation resilience in Azure deployments in the event of back-end service issues
* Include the server name in the new browser tab when using the Connect to Server feature
* Display the quantity of users in each group
* Enhanced resilience for the Connect to Server feature in all deployments
* Additional enhancements to setting MFA options for organizations and end users
** If SMS is set as the only MFA option available, require a phone number but not an email address
** If email is set as the only MFA option available, require an email address but not a phone number
** If both SMS and email are set as options for MFA, require both an email address and a phone number
* Clarity improvement - remove the size of an Azure Backup snapshot, as Azure doesn’t return the size of the snapshot
* Add the ability to delete a snapshot in non-Azure environments
* Bug fix for AVD host pool creation when using special characters
* Bug fix for workload scheduling for host pool via the Resources tab
* Bug fix for an error prompt that appears when cancelling a bulk user import
* Bug fix for a possible scenario with settings of application added to a Provisioning Collection
* Update to the email address sending notifications/messages – messages will now be sent from noreply@vds.netapp.com
** Customers safelisting inbound email addresses should add this email address


== VDS 6.0 release: Thursday April 29, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday April 29th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service
* Introduce Start on Connect feature for Personal AVD host pools
* Introduce Storage context in the Workspace module
* Introduce Storage (Azure NetApp Files) monitoring via Cloud Insights integration
** IOPs monitoring
** Latency monitoring
** Capacity monitoring
* Improved logging for VM Cloning actions
* Bug fix for a specific workload scheduling scenario
* Bug fix for not displaying a VM’s time zone in a certain scenario
* Bug fix for not logging out a AVD user in a certain scenario
* Updates to automatically generated emails to reflect NetApp branding

== VDS 6.0 hotfix: Friday April 16th, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Friday April 16th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Resolve an issue with automated certificate creation that arose after last night’s update that improved automated certificate management

== VDS 6.0 release: Thursday April 15, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday April 15th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Enhancements to the Cloud Insights integration:
** Frames Skipped – Insufficient Network Resources
** Frames Skipped – Insufficient Client Resources
** Frame Skipped – Insufficient Server Resources
** OS Disk – Read Bytes
** OS Disk – Write Bytes
** OS Disk – Read Bytes/second
** OS Disk – Write Bytes/second
* Update to task history in the Deployments module – improved handling of task history
* Bug fix for an issue where an Azure Backup couldn’t be restored to CWMGR1 from a disk in a subset of scenarios
* Bug fix for an issue where certificates weren’t automatically being updated and created
* Bug fix for an issue where a stopped deployment didn’t start quickly enough
* Update to the State drop-down list when creating a Workspace – remove the item “National” from the list
* Additional updates to reflect NetApp branding

== VDS 6.0 hotfix: Wednesday April 7th, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Wednesday April 7th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Due to increasingly variable response times from Azure, we are increasing the amount of time we wait for a response when entering Azure credentials during the deployment wizard.

== VDS 6.0 release: Thursday April 1, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday April 1st, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Updates to the NetApp Cloud Insights integration – new streaming data points:
** NVIDIA GPU performance data
** Round Trip Time
** User Input Delay
* Update the Connect to Server function to allow administrative connections to VMs even when VMs are set to disallow connections from end users
* API enhancements to enabled theming & branding in a subsequent release
* Improved visibility of the actions menu available in HTML5 connections via Connect to Server or RDS user sessions via HTML5
* Increase the QTY of characters supported in the name of an activity Scripted Events
* Updated Provisioning Collections OS choices by type
** For AVD and Windows 10, use the VDI collection type to ensure the Windows 10 OS is present
** For a Windows Server OS, use the Shared collection type
* Assorted proactive security and performance enhancements
