
////

Comments Sections:
Used in: sub.Reference.Release_Notes.vds_v6.0_release_notes.adoc

////

== VDS 6.0 hotfix: Friday April 16th, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Friday April 16th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Resolve an issue with automated certificate creation that arose after last night’s update that improved automated certificate management

== VDS 6.0 release: Thursday April 15, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday April 15th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Enhancements to the Cloud Insights integration:
** Frames Skipped – Insufficient Network Resources
** Frames Skipped – Insufficient Client Resources
** Frame Skipped – Insufficient Server Resources
** OS Disk – Read Bytes
** OS Disk – Write Bytes
** OS Disk – Read Bytes/second
** OS Disk – Write Bytes/second
* Update to task history in the Deployments module – improved handling of task history
* Bug fix for an issue where an Azure Backup couldn’t be restored to CWMGR1 from a disk in a subset of scenarios
* Bug fix for an issue where certificates weren’t automatically being updated and created
* Bug fix for an issue where a stopped deployment didn’t start quickly enough
* Update to the State drop-down list when creating a Workspace – remove the item “National” from the list
* Additional updates to reflect NetApp branding

== VDS 6.0 hotfix: Wednesday April 7th, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Wednesday April 7th, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Due to increasingly variable response times from Azure, we are increasing the amount of time we wait for a response when entering Azure credentials during the deployment wizard.

== VDS 6.0 release: Thursday April 1, 2021
_Components:_ 6.0 Virtual Desktop Service
_When:_ Thursday April 1st, 2021 at 10pm – 11pm Eastern
_Impact:_ Access to desktops and application services for End Users will remain uninterrupted. Access to Virtual Desktop Service will remain available.

=== Virtual Desktop Service

* Updates to the NetApp Cloud Insights integration – new streaming data points:
** NVIDIA GPU performance data
** Round Trip Time
** User Input Delay
* Update the Connect to Server function to allow administrative connections to VMs even when VMs are set to disallow connections from end users
* API enhancements to enabled theming & branding in a subsequent release
* Improved visibility of the actions menu available in HTML5 connections via Connect to Server or RDS user sessions via HTML5
* Increase the QTY of characters supported in the name of an activity Scripted Events
* Updated Provisioning Collections OS choices by type
** For WVD and Windows 10, use the VDI collection type to ensure the Windows 10 OS is present
** For a Windows Server OS, use the Shared collection type
* Assorted proactive security and performance enhancements
