=== Add Manual activity
In order for a script in the repository to take any action, an activity must be created to associate that script with a selected trigger. In this example activity execute when the VDS admin manually triggers the script.

VDS scripted events offers many other types of activity triggers such as _Create Server_ which could be used as an alternative to the _Manual_ event type. Using _Create Server_ would simply execute this script on all newly created VMs in VDS. _Create Server_ and other triggers are documented and can be explored link:Management.Scripted_Events.scripted_events.html[here].

.To create an Activity and link this script to an action:
. Navigate to the Scripted Events section in VDS
. Under _Activities_ click _+ Add Activity_
. In the opened dialog window enter the following information:
* *Name:* Name this activity
* *Description:* Optionally enter a description
* *Deployment* Select the desired deployment from dropdown
* *Script:* Select the install (or uninstall) script from the dropdown.  This could be the global script or customer script you've cloned and customized.
* *Arguments:* Leave blank
* *Enabled checkbox:* `Check` the box
* *Event Type:* Select `Manual` from dropdown
* *Target Type:* Select the `Servers` radio button
* *Managed Servers:* `Check` the box for each VM that should receive this uninstall.
