
////

Comments Sections:
Used in:


////

== Overview
_include/todo/Management.command_center.operations.add_existing_server_to_company.adoc
_include/todo/Management.command_center.operations.allow_new_wvd_connections.adoc
_include/todo/Management.command_center.operations.backup_list.adoc
_include/todo/Management.command_center.operations.backup_restore_to_drive.adoc
_include/todo/Management.command_center.operations.backup_server_now.adoc
_include/todo/Management.command_center.operations.backups_run_all_scheduled.adoc
_include/todo/Management.command_center.operations.change_data_home_pro_folders.adoc
_include/todo/Management.command_center.operations.change_password.adoc
_include/todo/Management.command_center.operations.copy_template_to_gallery.adoc
_include/todo/Management.command_center.operations.create_azure_file_share.adoc
_include/todo/Management.command_center.operations.create_azure_netapp_files_share.adoc
_include/todo/Management.command_center.operations.create_cache_company.adoc
_include/todo/Management.command_center.operations.create_data_center_site.adoc
_include/todo/Management.command_center.operations.create_no_server_company.adoc
_include/todo/Management.command_center.operations.create_server_from_backup.adoc
_include/todo/Management.command_center.operations.create_server_from_clone.adoc
_include/todo/Management.command_center.operations.create_server_from_template.adoc
_include/todo/Management.command_center.operations.create_template_phase_1.adoc
_include/todo/Management.command_center.operations.create_template_phase_3.adoc
_include/todo/Management.command_center.operations.created_company.adoc
_include/todo/Management.command_center.operations.delete_backup.adoc
_include/todo/Management.command_center.operations.delete_datacenter_site.adoc
_include/todo/Management.command_center.operations.delete_drives_from_server.adoc
_include/todo/Management.command_center.operations.delete_server.adoc
_include/todo/Management.command_center.operations.delete_template.adoc
_include/todo/Management.command_center.operations.edit_provisioning_collection.adoc
_include/todo/Management.command_center.operations.edit_resource_pool.adoc
_include/todo/Management.command_center.operations.edit_workload_schedule.adoc
_include/todo/Management.command_center.operations.exclude_server_from_monitoring.adoc
_include/todo/Management.command_center.operations.expand_drive.adoc
_include/todo/Management.command_center.operations.file_migration.adoc
_include/todo/Management.command_center.operations.generate_email_reports.adoc
_include/todo/Management.command_center.operations.generate_reports.adoc
_include/todo/Management.command_center.operations.install_notepad++_Chrome.adoc
_include/todo/Management.command_center.operations.install_thinprint_license_server.adoc
_include/todo/Management.command_center.operations.list_drives_for_server.adoc
_include/todo/Management.command_center.operations.list_long_running_operations.adoc
_include/todo/Management.command_center.operations.load_active_users.adoc
_include/todo/Management.command_center.operations.load_cache_companies.adoc
_include/todo/Management.command_center.operations.load_hypervisor_config_options.adoc
_include/todo/Management.command_center.operations.load_hypervisor_type.adoc
_include/todo/Management.command_center.operations.load_machine_series.adoc
_include/todo/Management.command_center.operations.load_machine_sizes.adoc
_include/todo/Management.command_center.operations.load_max_concurrent_users.adoc
_include/todo/Management.command_center.operations.load_resource_pool_data.adoc
_include/todo/Management.command_center.operations.load_server_resource_report_data.adoc
_include/todo/Management.command_center.operations.load_servers_for_company.adoc
_include/todo/Management.command_center.operations.load_storage_types.adoc
_include/todo/Management.command_center.operations.load_templates.adoc
_include/todo/Management.command_center.operations.load_virtual_machines.adoc
_include/todo/Management.command_center.operations.make_server_active.adoc
_include/todo/Management.command_center.operations.make_server_data_server.adoc
_include/todo/Management.command_center.operations.migrate_company.adoc
_include/todo/Management.command_center.operations.move_servers_to_company.adoc
_include/todo/Management.command_center.operations.reboot_server.adoc
_include/todo/Management.command_center.operations.reload_configuration.adoc
_include/todo/Management.command_center.operations.reload_monitored_applications.adoc
_include/todo/Management.command_center.operations.remove_vds_software.adoc
_include/todo/Management.command_center.operations.rename_server.adoc
_include/todo/Management.command_center.operations.resource_allocation_enable.adoc
_include/todo/Management.command_center.operations.run_daily_actions.adoc
_include/todo/Management.command_center.operations.run_daily_maintenance.adoc
_include/todo/Management.command_center.operations.run_program.adoc
_include/todo/Management.command_center.operations.run_resource_allocation.adoc
_include/todo/Management.command_center.operations.run_workload_schedule.adoc
_include/todo/Management.command_center.operations.set_external_dns.adoc
_include/todo/Management.command_center.operations.set_gateway_address.adoc
_include/todo/Management.command_center.operations.set_time_zone.adoc
_include/todo/Management.command_center.operations.should_pool_be_running.adoc
_include/todo/Management.command_center.operations.start_company.adoc
_include/todo/Management.command_center.operations.start_server_for_wake_on_demand.adoc
_include/todo/Management.command_center.operations.start_server.adoc
_include/todo/Management.command_center.operations.stop_company.adoc
_include/todo/Management.command_center.operations.stop_cwagent.adoc
_include/todo/Management.command_center.operations.stop_sddc.adoc
_include/todo/Management.command_center.operations.stop_server.adoc
_include/todo/Management.command_center.operations.test_hypervisor_connection.adoc
_include/todo/Management.command_center.operations.update_active_user_count.adoc
_include/todo/Management.command_center.operations.update_cw_vm_automation_service.adoc
_include/todo/Management.command_center.operations.wildcard_cert_create_new.adoc
_include/todo/Management.command_center.operations.wildcard_cert_install.adoc
